### ISSUE TITLE
Add testing data files for VCF and BCF format

### ISSUE THREAD

**Issue by chris-zen** [chris-zen/htsget-mvp#2]
So we can develop and test searches for variants

**Comment by brainstorm** [comment]
Any particular requirements for this one? Using the [Noodles VCF writer](https://github.com/zaeleus/noodles/blob/master/noodles-vcf/examples/vcf_write.rs) should be fairly straightforward.

**Comment by chris-zen** [comment]
Can we take this?
https://github.com/googlegenomics/htsget/tree/master/internal/bcf/testdata
